name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.5.4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: v1.18.0

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Kubernetes credentials
      run: |
        az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install hello_ip ./hello_ip
